# Generated by Django 6.0.1 on 2026-01-17 14:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginationsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
